name: Deployment Workflow

# Trigger this workflow on pushes to the specified branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Build Next.js app
        run: pnpm run build

      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            .next
            package.json
            pnpm-lock.yaml

      - uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      - name: Push Standalone Build to Droplet
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete -I
          path: build/
          remote_path: /var/www/payitfwd.in
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.FINGERPRINT }}

      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} # Your server's IP address
          username: ${{ secrets.USERNAME }} # Your server's username
          key: ${{ secrets.FINGERPRINT }} # Your server's SSH private key
          script: |
            cd /var/www/payitfwd.in
            pnpm i
            pm2 delete payitfwd.in 2> /dev/null && pm2 start pnpm --name "payitfwd.in" -- start
            pm2 save
