name: Deployment Workflow

# Trigger this workflow on pushes to the specified branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Build Next.js app
        run: pnpm run build

      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            .next
            package.json
            pnpm-lock.yaml

      - uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      - name: Push Standalone Build to Droplet
        run: |
          mkdir -vm 700 $HOME/.ssh
          ssh-keyscan -Ht ed25519 ${{ secrets.HOST }} > $HOME/.ssh/known_hosts
          echo "${{ secrets.FINGERPRINT }}" > $HOME/.ssh/id_ed25519
          chmod 600 $HOME/.ssh/id_ed25519
          scp build/* ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/var/www/payitfwd.in/build

      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} # Your server's IP address
          username: ${{ secrets.USERNAME }} # Your server's username
          key: ${{ secrets.FINGERPRINT }} # Your server's SSH private key
          script: |
            cd /var/www/payitfwd.com
            mv build/* .
            rm -r build
            pnpm i
            pm2 delete payitfwd.com 2> /dev/null && pm2 start pnpm --name "payitfwd.com" -- start
            pm2 save
